# Generated by Django 5.2.13 on 2026-05-13 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='operating_contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant FCFA verse au Budget General EVE pour la duree du projet.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='operating_contribution_note',
            field=models.TextField(blank=True, help_text="Note libre quand le mecanisme n'est pas un pourcentage unique (lignes eparses, a documenter, etc.)."),
        ),
        migrations.AddField(
            model_name='project',
            name='operating_contribution_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux conventionnel (% sur total direct ou HT selon le bailleur).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
