# Generated by Django 5.2.13 on 2026-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bankaccount_bankaccountsnapshot'),
        ('projects', '0002_project_operating_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, help_text='Comptes bancaires EVE associes au projet.', related_name='projects', to='finance.bankaccount'),
        ),
    ]
