# Generated by Django 5.2.13 on 2026-06-10 21:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_bank_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administration_split_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text="SYCEBNL : pourcentage du decaissement bailleur affecte au Fonds d'administration (compte 462) - destine aux charges de fonctionnement. Somme avec investment_split_pct doit faire 100.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='investment_split_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="SYCEBNL : pourcentage du decaissement bailleur affecte aux Fonds d'investissement (compte 162) - destine aux acquisitions d'immobilisations. Default 0 (EVE est majoritairement fonctionnement).", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
