# Generated by Django 5.2.7 on 2026-06-20 01:12

import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_bankmovement_idempotent_conditional'),
        ('hr', '0003_employee_assignment_label_and_more'),
        ('projects', '0004_sycebnl_split_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('investment_split_pct', django.db.models.expressions.CombinedExpression(models.Value(Decimal('100.00')), '-', models.F('administration_split_pct')))), name='project_invest_admin_split_sum_100'),
        ),
    ]
