# Generated by Django 5.2.15 on 2026-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('projects', '0005_project_project_invest_admin_split_sum_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='validator_roles',
            field=models.ManyToManyField(blank=True, help_text='Roles qui valident les demandes de depense de CE projet. Vide = trio par defaut RAF/DP/SE. Ex. Saint-Louis : RAF/REFERENT_TECH/SE (le Referent technique remplace la DP).', related_name='validated_projects', to='accounts.role'),
        ),
    ]
