# Generated by Django 5.2.13 on 2026-04-25 00:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commitment_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('commitment_type', models.CharField(blank=True, choices=[('BON_COMMANDE', 'Bon de commande'), ('CONTRAT_FOURNISSEUR', 'Contrat fournisseur'), ('ACHAT_DIRECT', 'Achat direct'), ('MISSION', 'Mission')], max_length=30)),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('supplier_nif', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commitment_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOLDE', 'Solde'), ('ANNULE', 'Annule')], default='EN_COURS', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('document_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'commitments',
                'ordering': ['-commitment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('payment_method', models.CharField(blank=True, choices=[('VIREMENT', 'Virement'), ('ESPECES', 'Especes'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile money')], max_length=20)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('beneficiary_account', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('bank_reference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Valide'), ('ANNULE', 'Annule')], default='VALIDE', max_length=20)),
            ],
            options={
                'db_table': 'disbursements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportingDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('FACTURE', 'Facture'), ('RECU', 'Recu'), ('DEVIS', 'Devis'), ('CONTRAT', 'Contrat'), ('BON_LIVRAISON', 'Bon de livraison'), ('AUTRE', 'Autre')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('file_url', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supporting_docs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='activities.activity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budget_lines', to='references.budgetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_lines',
                'ordering': ['project__code', 'category__code', 'description'],
            },
        ),
    ]
