# Generated by Django 5.2.13 on 2026-05-13 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budgetline_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Nom interne EVE du compte (ex: 'EVE-OXFAM', 'EVE service').", max_length=100, unique=True)),
                ('bank_name', models.CharField(blank=True, help_text="Nom de la banque (ex: 'SUNU BANK SENEGAL', 'CBAO', 'BOA').", max_length=100)),
                ('account_reference', models.CharField(blank=True, help_text='RIB / IBAN si renseigne (libre).', max_length=50)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, help_text="Solde d'ouverture connu (au plus recent snapshot).", max_digits=14, null=True)),
                ('opening_date', models.DateField(blank=True, help_text="Date du solde d'ouverture / dernier rapprochement.", null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_note', models.TextField(blank=True, help_text='Source du chiffre (releve bancaire, rapprochement compta, etc.).')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_account_snapshots',
                'ordering': ['account__name', '-date'],
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='uq_bank_account_snapshot_per_date')],
            },
        ),
    ]
