# Generated by Django 5.2.13 on 2026-05-13 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bankaccount_bankaccountsnapshot'),
        ('projects', '0003_project_bank_accounts'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='Libelle de la ligne tel que ecrit dans le plan source.', max_length=200)),
                ('direction', models.CharField(choices=[('ENCAISSEMENT', 'Encaissement'), ('DECAISSEMENT', 'Decaissement')], max_length=20)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant reel constate (mois revolu). None = pas encore renseigne.', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_entries', to='references.budgetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_entries', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cashflow_entries',
                'ordering': ['period_year', 'period_month', 'direction', 'label'],
                'constraints': [models.UniqueConstraint(fields=('period_year', 'period_month', 'label', 'direction'), name='uq_cashflow_entry_per_period_label_direction')],
            },
        ),
    ]
