# Generated by Django 5.2.13 on 2026-05-13 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cashflowentry'),
        ('projects', '0003_project_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_operation', models.DateField(help_text="Date d'operation telle qu'imprimee sur le releve.")),
                ('date_value', models.DateField(blank=True, help_text='Date de valeur, si differente.', null=True)),
                ('reference', models.CharField(blank=True, help_text='Reference banque (ex: G167265, F856524).', max_length=50)),
                ('label', models.CharField(help_text='Libelle complet du mouvement tel que sur le releve.', max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Solde apres operation tel que sur le releve.', max_digits=14, null=True)),
                ('source_document', models.CharField(blank=True, help_text="Document source (ex: 'Releve Banque Atlantique decembre 2025').", max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finance.bankaccount')),
                ('cashflow_entry', models.ForeignKey(blank=True, help_text='Ligne de plan tresorerie matchee, si applicable (suivi reel/prevu).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='finance.cashflowentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Projet auquel le mouvement se rapporte, si identifiable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_movements',
                'ordering': ['-date_operation', '-id'],
                'indexes': [models.Index(fields=['account', '-date_operation'], name='bank_moveme_account_5a4ff9_idx'), models.Index(fields=['reference'], name='bank_moveme_referen_f19f28_idx')],
            },
        ),
    ]
