# Generated by Django 5.2.13 on 2026-05-13 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bankmovement'),
        ('projects', '0003_project_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_operation', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commentary', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cash_movements',
                'ordering': ['-date_operation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Caisse centrale BG', max_length=80, unique=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cash_registers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text='Imputation analytique : ligne budgetaire (BG ou projet) eligible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='finance.budgetline'),
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='commentary',
            field=models.TextField(blank=True, help_text="Justification metier de l'operation (numero piece, beneficiaire reel, motif)."),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Projet auquel le mouvement se rapporte. Cohere avec budget_line.project quand les deux sont renseignes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='bankmovement',
            index=models.Index(fields=['budget_line'], name='bank_moveme_budget__e22335_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankmovement',
            constraint=models.UniqueConstraint(fields=('account', 'date_operation', 'reference', 'debit', 'credit'), name='uq_bank_movement_idempotent_key'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='finance.budgetline'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='projects.project'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='finance.cashregister'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['register', '-date_operation'], name='cash_moveme_registe_e1b233_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['budget_line'], name='cash_moveme_budget__a1a5ea_idx'),
        ),
    ]
