# Generated by Django 5.2.13 on 2026-05-13 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_cashmovement_cashregister_bankmovement_budget_line_and_more'),
        ('projects', '0003_project_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('class_number', models.PositiveSmallIntegerField(choices=[(1, '1 - Fonds propres et fonds dedies'), (2, '2 - Immobilisations'), (3, '3 - Stocks'), (4, '4 - Tiers'), (5, '5 - Tresorerie'), (6, '6 - Charges'), (7, '7 - Produits'), (8, '8 - Engagements hors bilan')])),
                ('is_liaison', models.BooleanField(default=False, help_text='Compte de liaison interne (18x : flux projet <-> BG).')),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_bank_account', models.ForeignKey(blank=True, help_text='Compte bancaire reel associe (pour les comptes 512.x).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_account', to='finance.bankaccount')),
                ('linked_cash_register', models.ForeignKey(blank=True, help_text='Caisse reelle associee (pour les comptes 571.x).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_account', to='finance.cashregister')),
                ('linked_project', models.ForeignKey(blank=True, help_text='Projet associe (pour les comptes de liaison 181.x).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_accounts', to='projects.project')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='contra_account',
            field=models.ForeignKey(blank=True, help_text='Compte SYCEBNL contrepartie (charge 6x, produit 7x, liaison 18x).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements_contra', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='contra_account',
            field=models.ForeignKey(blank=True, help_text='Compte SYCEBNL contrepartie (charge 6x, produit 7x, liaison 18x).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_contra', to='finance.chartofaccount'),
        ),
    ]
