# Generated by Django 5.2.13 on 2026-05-13 20:10

import apps.finance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('finance', '0008_chartofaccount_bankmovement_contra_account_and_more'),
        ('hr', '0003_employee_assignment_label_and_more'),
        ('projects', '0003_project_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Intitule court de la demande.', max_length=200)),
                ('motif', models.TextField(help_text='Justification metier detaillee.')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Rejetee'), ('EXECUTED', 'Executee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('budget_line', models.ForeignKey(help_text='Ligne budgetaire eligible.', on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='finance.budgetline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executed_bank_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_expense_requests', to='finance.bankmovement')),
                ('executed_cash_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_expense_requests', to='finance.cashmovement')),
                ('project', models.ForeignKey(blank=True, help_text="Projet d'imputation. Null = Budget General.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='projects.project')),
                ('requester', models.ForeignKey(help_text='Employe initiateur (responsable projet).', on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests_created', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('PROFORMA', 'Facture proforma / contrat (initial)'), ('BC', 'Bon de commande'), ('PV_SELECTION', 'PV de selection'), ('FACTURE', 'Facture definitive'), ('RAPPORT', 'Rapport / livrable'), ('AUTRE', 'Autre justificatif')], max_length=20)),
                ('file', models.FileField(upload_to=apps.finance.models._expense_doc_upload_to)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.expenserequest')),
            ],
            options={
                'db_table': 'expense_documents',
                'ordering': ['request_id', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Rejetee')], default='PENDING', max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='finance.expenserequest')),
                ('role', models.ForeignKey(help_text='Role attendu (RAF, DP, SE).', on_delete=django.db.models.deletion.PROTECT, related_name='expense_validations', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validator', models.ForeignKey(blank=True, help_text='Utilisateur ayant pris la decision (rempli au moment de signer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_validations_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_validations',
                'ordering': ['request_id', 'role__code'],
                'constraints': [models.UniqueConstraint(fields=('request', 'role'), name='uq_expense_validation_per_role')],
            },
        ),
    ]
