# Generated by Django 5.2.13 on 2026-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_journalentry_journalline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='justification',
            field=models.FileField(blank=True, help_text='Piece justificative (ticket, recu, facturette) - photo ou PDF.', null=True, upload_to='cash_justifications/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='recipient',
            field=models.CharField(blank=True, help_text='Beneficiaire de la sortie de caisse (nom, prestataire, etc.).', max_length=150),
        ),
    ]
