# Generated by Django 5.2.13 on 2026-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_cashmovement_justification_cashmovement_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovement',
            name='justification',
            field=models.FileField(blank=True, help_text='Piece justificative scannee (facture, ordre virement, avis credit).', null=True, upload_to='bank_justifications/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='recipient',
            field=models.CharField(blank=True, help_text='Beneficiaire de la sortie ou source du credit (nom employe, fournisseur, bailleur).', max_length=200),
        ),
    ]
