# Generated by Django 5.2.13 on 2026-06-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_bankmovement_justification_bankmovement_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.FileField(help_text='PDF du releve bancaire original.', upload_to='bank_statements/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon en revue'), ('IMPORTED', 'Importe'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=20)),
                ('parsed_lines', models.JSONField(default=list, help_text='Liste des lignes extraites du PDF avec auto-suggestion. Chaque entree: {date_operation, label, debit, credit, suggested_contra_code, suggested_contra_name, raw_text}.')),
                ('nb_lines_parsed', models.PositiveIntegerField(default=0)),
                ('nb_lines_imported', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_imports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_statement_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
