# Generated by Django 5.2.13 on 2026-06-10 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_bankstatementimport'),
        ('projects', '0003_project_bank_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, help_text="Detail de la ligne (ex: 'Salaire animateur 1 janvier 2026').", max_length=300)),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_allocations', to='finance.budgetline')),
                ('contra_account', models.ForeignKey(help_text='Compte SYCEBNL de charge (6x) ou de produit (7x) pour cette ligne.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_allocations', to='finance.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.bankmovement')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_allocations', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_movement_allocations',
                'ordering': ['movement_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankMovementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('TDR', 'Termes de reference'), ('PROFORMA', 'Facture proforma'), ('CONTRAT', 'Contrat / convention'), ('AVENANT', 'Avenant au contrat'), ('PV_SELECTION', 'PV de selection fournisseur'), ('BC', 'Bon de commande'), ('FACTURE', 'Facture definitive'), ('BORDEREAU', 'Bordereau de livraison'), ('PRESENCE', 'Feuille de presence'), ('RAPPORT', 'Rapport activite / livrable'), ('ORDRE_VIREMENT', 'Ordre de virement bancaire'), ('AVIS_CREDIT', 'Avis de credit bancaire'), ('RELEVE', 'Extrait de releve bancaire'), ('AUTRE', 'Autre piece')], max_length=25)),
                ('file', models.FileField(upload_to='bank_documents/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.bankmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_movement_documents',
                'ordering': ['movement_id', 'document_type'],
            },
        ),
    ]
