# Generated by Django 5.2.13 on 2026-06-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_remap_bank_sub_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='class_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Fonds propres et fonds dedies'), (2, '2 - Immobilisations'), (3, '3 - Stocks'), (4, '4 - Tiers'), (5, '5 - Tresorerie'), (6, '6 - Charges'), (7, '7 - Produits'), (8, '8 - Engagements hors bilan'), (9, '9 - Contributions volontaires en nature')]),
        ),
    ]
