# Generated by Django 5.2.7 on 2026-06-11 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_add_class9_voluntary_contributions'),
        ('projects', '0004_sycebnl_split_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankmovement',
            name='uq_bank_movement_idempotent_key',
        ),
        migrations.AddConstraint(
            model_name='bankmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('reference', ''), _negated=True)), fields=('account', 'date_operation', 'reference', 'debit', 'credit'), name='uq_bank_movement_idempotent_key'),
        ),
    ]
