# Generated by Django 5.2.13 on 2026-06-26 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_bankmovement_idempotent_conditional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='charge_account',
            field=models.ForeignKey(blank=True, help_text="Compte de charge 6x impute a l'engagement (Dr 6x / Cr 401.x).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments_as_charge', to='finance.chartofaccount'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, help_text='Code interne stable (F001, F002, ...). Genere si vide.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('nif', models.CharField(blank=True, help_text="Numero d'Identification Fiscale (facultatif).", max_length=30)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_service_provider', models.BooleanField(default=False, help_text='Prestataire de services (soumis a la retenue a la source 5% - phase ulterieure).')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='linked_supplier',
            field=models.ForeignKey(blank=True, help_text='Fournisseur associe (pour les sous-comptes auxiliaires 401.x).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_accounts', to='finance.supplier'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text="Fournisseur (master). Son sous-compte 401.x est credite a l'engagement.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='finance.supplier'),
        ),
    ]
