# Generated by Django 5.2.13 on 2026-06-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_backfill_suppliers_from_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_commitment',
            field=models.OneToOneField(blank=True, help_text="Engagement (Commitment) a l'origine de l'ecriture d'engagement (Dr 6x / Cr 401.x + neutralisation Dr 462 / Cr 702).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='finance.commitment'),
        ),
    ]
