# Generated by Django 5.2.15 on 2026-07-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_journalentry_source_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='commitment',
            field=models.OneToOneField(blank=True, help_text="Engagement SYCEBNL lie a cette demande (cree a l'etape Engager).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_request', to='finance.commitment'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('APPROVED', 'Approuvee'), ('ENGAGED', 'Engagee'), ('LIQUIDATED', 'Liquidee (facture constatee)'), ('REJECTED', 'Rejetee'), ('EXECUTED', 'Executee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=20),
        ),
    ]
