# Generated by Django 5.2.13 on 2026-04-25 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assignment_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_source',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='workforce_category',
            field=models.CharField(choices=[('SALARIE', 'Salarie / Contractuel'), ('PRESTATAIRE', 'Prestataire terrain'), ('CONSULTANT', 'Consultant / Expert')], default='SALARIE', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkforceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('scope', models.CharField(blank=True, max_length=180)),
                ('source_date', models.DateField()),
                ('reported_total_staff', models.PositiveIntegerField(default=0)),
                ('detailed_total_staff', models.PositiveIntegerField(default=0)),
                ('salaried_and_contractual_count', models.PositiveIntegerField(default=0)),
                ('service_provider_count', models.PositiveIntegerField(default=0)),
                ('consultant_count', models.PositiveIntegerField(default=0)),
                ('relay_worker_count', models.PositiveIntegerField(default=0)),
                ('icp_count', models.PositiveIntegerField(default=0)),
                ('health_post_count', models.PositiveIntegerField(default=0)),
                ('companion_count', models.PositiveIntegerField(default=0)),
                ('community_supervisor_count', models.PositiveIntegerField(default=0)),
                ('covered_regions_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workforce_snapshots',
                'ordering': ['-source_date', 'reference_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=150)),
                ('relay_worker_count', models.PositiveIntegerField(default=0)),
                ('support_structures', models.CharField(blank=True, max_length=180)),
                ('beneficiary_scope', models.CharField(blank=True, max_length=180)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographies', to='hr.workforcesnapshot')),
            ],
            options={
                'db_table': 'workforce_geographies',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
