# Generated by Django 5.2.13 on 2026-04-25 00:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_type', models.CharField(blank=True, choices=[('PHOTO', 'Photo'), ('PRESENCE_LIST', 'Presence list'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('GPS', 'GPS')], max_length=20)),
                ('file_url', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_evidences',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'activity_locations',
            },
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('actual_location', models.CharField(blank=True, max_length=200)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('participants_count', models.PositiveIntegerField(blank=True, null=True)),
                ('male_count', models.PositiveIntegerField(blank=True, null=True)),
                ('female_count', models.PositiveIntegerField(blank=True, null=True)),
                ('children_count', models.PositiveIntegerField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('SOUMIS', 'Soumis'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='SOUMIS', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_card_number', models.CharField(blank=True, max_length=30)),
                ('signature_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'beneficiaries',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(blank=True, max_length=40)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('planned_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('EN_COURS', 'En cours'), ('REALISE', 'Realise'), ('ANNULE', 'Annule')], default='PLANIFIE', max_length=20)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['project__code', 'planned_start_date', 'title'],
            },
        ),
    ]
