# Generated by Django 5.2.13 on 2026-05-14 18:27

import apps.activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityevidence',
            name='file_url',
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='file',
            field=models.FileField(default='', upload_to=apps.activities.models._activity_evidence_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='validation_comment',
            field=models.TextField(blank=True, help_text='Commentaire du valideur (Suivi & Evaluation), notamment en cas de rejet.'),
        ),
    ]
