# Generated by Django 5.2.13 on 2026-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activityevidence_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='planned_start_date',
            field=models.DateField(blank=True, help_text="Date de debut prevue. Peut etre vide pour une activite issue d'un cadre logique non encore calendarise ; la saisie manuelle l'exige.", null=True),
        ),
    ]
