# Generated by Django 5.2.7 on 2026-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_planned_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='validation_comment',
            field=models.TextField(blank=True, help_text='Commentaire du valideur (Secretaire Executif), notamment en cas de rejet.'),
        ),
    ]
