from datetime import date


RH_REFERENCE_CODE = "RH-2025-2026"
RH_REFERENCE_SOURCE = "PDF_RH_EVE_2025_2026"


RH_REFERENCE_SNAPSHOT = {
    "reference_code": RH_REFERENCE_CODE,
    "title": "Tableau de Bord RH EVE 2025-2026",
    "scope": "Senegal - Projets 2025-2026",
    "source_date": date(2026, 4, 23),
    "reported_total_staff": 33,
    "detailed_total_staff": 35,
    "salaried_and_contractual_count": 22,
    "service_provider_count": 11,
    "consultant_count": 2,
    "relay_worker_count": 572,
    "icp_count": 25,
    "health_post_count": 34,
    "companion_count": 54,
    "community_supervisor_count": 10,
    "covered_regions_count": 3,
    "notes": (
        "Source PDF datee du 23 avril 2026. Les listes detaillees du personnel "
        "consolident 35 personnes (22 salaries/contractuels, 11 prestataires, 2 consultants) "
        "alors que le cartouche de synthese du document mentionne 33."
    ),
}


RH_REFERENCE_GEOGRAPHIES = [
    {
        "sort_order": 1,
        "label": "Saint-Louis - Nous-Cims",
        "relay_worker_count": 60,
        "support_structures": "25 ICP + equipe cadre du district",
        "beneficiary_scope": "3 748 enfants de 6-59 mois",
    },
    {
        "sort_order": 2,
        "label": "Pikine / Mbao - Nous-Cims Agir",
        "relay_worker_count": 102,
        "support_structures": "34 postes de sante",
        "beneficiary_scope": "7 081 menages",
    },
    {
        "sort_order": 3,
        "label": "Kedougou - PNBSF",
        "relay_worker_count": 142,
        "support_structures": "10 superviseurs communautaires",
        "beneficiary_scope": "Zones rurales et urbaines",
    },
    {
        "sort_order": 4,
        "label": "Dakar - PNBSF (67 quartiers)",
        "relay_worker_count": 268,
        "support_structures": "54 accompagnateurs",
        "beneficiary_scope": "268 groupes ACEC / AVEC actifs",
    },
]


RH_REFERENCE_COMMUNES = [
    {"code": "PKO", "name": "Pikine Ouest", "department": "Pikine", "region": "Dakar"},
    {"code": "PKN", "name": "Pikine", "department": "Pikine", "region": "Dakar"},
    {"code": "MBA", "name": "Mbao", "department": "Pikine", "region": "Dakar"},
    {"code": "GRN", "name": "Guinaw Rails Nord", "department": "Pikine", "region": "Dakar"},
    {"code": "PAR", "name": "Parcelles Assainies", "department": "Dakar", "region": "Dakar"},
    {"code": "CAM", "name": "Camberene", "department": "Dakar", "region": "Dakar"},
    {"code": "KMS", "name": "Keur Massar", "department": "Keur Massar", "region": "Dakar"},
    {"code": "STL", "name": "Saint-Louis", "department": "Saint-Louis", "region": "Saint-Louis"},
    {"code": "KDG", "name": "Kedougou", "department": "Kedougou", "region": "Kedougou"},
    {"code": "BKL", "name": "Bakel", "department": "Bakel", "region": "Tambacounda"},
]


RH_REFERENCE_PROJECTS = [
    {
        "code": "NOUSCIMS-SL-2026",
        "title": "Projet Nutrition Saint-Louis (Nous-Cims)",
        "short_title": "Nous-Cims Saint-Louis",
        "sector": "NUTRITION",
        "target_beneficiaries": 3748,
        "partner_name": "Fondation Nous-Cims",
    },
    {
        "code": "NOUSCIMS-PIK-MBAO-2026",
        "title": "Agir - Pikine / Mbao (Nous-Cims Phase II Ext.)",
        "short_title": "Nous-Cims Pikine / Mbao",
        "sector": "NUTRITION",
        "target_beneficiaries": 7081,
        "partner_name": "Fondation Nous-Cims",
    },
    {
        "code": "PNBSF-KED-2026",
        "title": "PNBSF - OS Kedougou",
        "short_title": "PNBSF Kedougou",
        "sector": "ENVIRONNEMENT",
        "target_beneficiaries": 7081,
        "partner_name": "DGPSN",
    },
    {
        "code": "PNBSF-DAK-2026",
        "title": "PNBSF - OS Dakar",
        "short_title": "PNBSF Dakar",
        "sector": "ENVIRONNEMENT",
        "target_beneficiaries": 268,
        "partner_name": "DGPSN",
    },
]


RH_REFERENCE_PERSONNEL = [
    {
        "matricule": "REF-2026-001",
        "first_name": "Aly",
        "last_name": "DIOUF",
        "category": "SALARIE",
        "position": "Responsable",
        "department": "Direction generale",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-002",
        "first_name": "Abdou",
        "last_name": "DIOUF",
        "category": "SALARIE",
        "position": "Administration / Finances",
        "department": "Administration / Finances",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-003",
        "first_name": "Seynabou Mbaye",
        "last_name": "NDIAYE",
        "category": "SALARIE",
        "position": "Collaboratrice siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-004",
        "first_name": "Adiouma",
        "last_name": "NDIONGUE",
        "category": "SALARIE",
        "position": "Collaboratrice siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-005",
        "first_name": "Cheikh Pathe",
        "last_name": "FALL",
        "category": "SALARIE",
        "position": "Collaborateur siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-006",
        "first_name": "Serigne Souaibou",
        "last_name": "SAKHO",
        "category": "SALARIE",
        "position": "Collaborateur siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-007",
        "first_name": "Cecile Constance",
        "last_name": "TINE",
        "category": "SALARIE",
        "position": "Collaboratrice siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-008",
        "first_name": "Mor",
        "last_name": "NDIAYE",
        "category": "SALARIE",
        "position": "Collaborateur siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-009",
        "first_name": "Amy",
        "last_name": "SECK",
        "category": "SALARIE",
        "position": "Collaboratrice siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-010",
        "first_name": "Papa Ousseynou",
        "last_name": "SECK",
        "category": "SALARIE",
        "position": "Collaborateur siege",
        "department": "Siege EVE",
        "organizational_unit": "Equipe Siege EVE",
        "assignment_label": "Siege EVE",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-011",
        "first_name": "Moustapha",
        "last_name": "FALL",
        "category": "SALARIE",
        "position": "Chef de projet S&E",
        "department": "Programmes",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Nous-Cims Saint-Louis",
        "commune_code": "STL",
        "project_code": "NOUSCIMS-SL-2026",
    },
    {
        "matricule": "REF-2026-012",
        "first_name": "Diouma",
        "last_name": "NDOUR",
        "category": "SALARIE",
        "position": "Point Focal Projet",
        "department": "Programmes",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Nous-Cims Pikine / OXFAM",
        "commune_code": "PKN",
        "project_code": "NOUSCIMS-PIK-MBAO-2026",
    },
    {
        "matricule": "REF-2026-013",
        "first_name": "Khalifa Ababacar",
        "last_name": "DIENG",
        "category": "SALARIE",
        "position": "Animateur Concertations",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Nous-Cims Pikine",
        "commune_code": "PKN",
        "project_code": "NOUSCIMS-PIK-MBAO-2026",
    },
    {
        "matricule": "REF-2026-014",
        "first_name": "El Hadji Habib Timack",
        "last_name": "DIOUF",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-015",
        "first_name": "Papa Iba Mar",
        "last_name": "FALL",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-016",
        "first_name": "Farma",
        "last_name": "DIEYE",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-017",
        "first_name": "Khady",
        "last_name": "SYLLA",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-018",
        "first_name": "Magueye",
        "last_name": "DRAME",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-019",
        "first_name": "Ndiare",
        "last_name": "NDIAYE",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-020",
        "first_name": "Alassane",
        "last_name": "BA",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-021",
        "first_name": "Youssoupha",
        "last_name": "SY",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-022",
        "first_name": "Rokhaya",
        "last_name": "BA",
        "category": "SALARIE",
        "position": "Agent terrain",
        "department": "Terrain",
        "organizational_unit": "Equipe Projets / Terrain",
        "assignment_label": "Projet terrain",
        "commune_code": "PKN",
    },
    {
        "matricule": "REF-2026-023",
        "first_name": "Abdoulaye",
        "last_name": "BA",
        "category": "PRESTATAIRE",
        "position": "Point Focal Logistique",
        "department": "Logistique",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "Coordination terrain",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-024",
        "first_name": "Ismaila",
        "last_name": "BALDE",
        "category": "PRESTATAIRE",
        "position": "Superviseur - Zone Bakel",
        "department": "Terrain",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "PNBSF / Kedougou",
        "commune_code": "BKL",
        "project_code": "PNBSF-KED-2026",
    },
    {
        "matricule": "REF-2026-025",
        "first_name": "Abdoulaye",
        "last_name": "TOURE",
        "category": "PRESTATAIRE",
        "position": "Superviseur - Zone Parcelles / Camberene",
        "department": "Terrain",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "PNBSF Dakar",
        "commune_code": "PAR",
        "project_code": "PNBSF-DAK-2026",
    },
    {
        "matricule": "REF-2026-026",
        "first_name": "Moustapha",
        "last_name": "SENE",
        "category": "PRESTATAIRE",
        "position": "Superviseur - Zone Keur Massar / Mbao",
        "department": "Terrain",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "PNBSF Dakar",
        "commune_code": "KMS",
        "project_code": "PNBSF-DAK-2026",
    },
    {
        "matricule": "REF-2026-027",
        "first_name": "Amy",
        "last_name": "SANE",
        "category": "PRESTATAIRE",
        "position": "Magasiniere Centrale",
        "department": "Logistique",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "PNBSF Dakar",
        "commune_code": "PKO",
        "project_code": "PNBSF-DAK-2026",
    },
    {
        "matricule": "REF-2026-028",
        "first_name": "Aboubacar",
        "last_name": "NDONGO",
        "category": "PRESTATAIRE",
        "position": "Magasinier Central",
        "department": "Logistique",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "PNBSF Bakel",
        "commune_code": "BKL",
    },
    {
        "matricule": "REF-2026-029",
        "first_name": "Assietou Tenemba",
        "last_name": "NDIAYE",
        "category": "PRESTATAIRE",
        "position": "Animatrice",
        "department": "Terrain",
        "organizational_unit": "Prestataires terrain",
        "assignment_label": "Guinaw Rails Nord",
        "commune_code": "GRN",
        "project_code": "PNBSF-DAK-2026",
    },
    {
        "matricule": "REF-2026-030",
        "first_name": "Pierre Simon Daniel Mbad",
        "last_name": "NDIAYE",
        "category": "CONSULTANT",
        "position": "Expert consultant",
        "department": "Appui technique",
        "organizational_unit": "Consultants / Experts",
        "assignment_label": "Multi-projets",
        "commune_code": "PKO",
    },
    {
        "matricule": "REF-2026-031",
        "first_name": "Adrien",
        "last_name": "COLY",
        "category": "CONSULTANT",
        "position": "Expert consultant",
        "department": "Appui technique",
        "organizational_unit": "Consultants / Experts",
        "assignment_label": "Multi-projets",
        "commune_code": "PKO",
    },
]
